### ISSUE TITLE
Better Battery Templates for z-wave battery powered devices

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#104]
```
battery_level_warning:
        friendly_name: 'Front Sensor Battery Level Warning'
        value_template: >
          {% if states('sensor.aeotec_zw100_multisensor_6_battery_level_5_0') | float < 10 or
                states('sensor.aeotec_zw120_door_window_sensor_gen5_battery_level_8_0') | float < 10 or
                states('sensor.aeotec_zw120_door_window_sensor_gen5_battery_level_9_0') | float < 10
          %}
            Replace
          {% elif states('sensor.aeotec_zw100_multisensor_6_battery_level_5_0') | float < 25 or
                  states('sensor.aeotec_zw120_door_window_sensor_gen5_battery_level_8_0') | float < 25 or
                  states('sensor.aeotec_zw120_door_window_sensor_gen5_battery_level_9_0') | float < 25 
          %}
            Low
          {% else %}
            Good
          {% endif %}
```

**Comment by brianjking** [comment]
```
  - alias: Battery level low
    trigger:
      platform: state
      entity_id: sensor.battery_level_warning
      state: 'Low'
    action:
      - service: tts.google_say
        entity_id: media_player.office_google_home
        data:
          message: 'Sensor battery low.'
      - service: notify.nexus5x
        data:
          title: 'Sensor battery low'
          message: 'Sensor battery low.'

  - alias: Replace battery
    trigger:
      platform: state
      entity_id: sensor.battery_level_warning
      state: 'Replace'
    action:
      - service: tts.google_say
        entity_id: media_player.office_google_home
        data:
          message: 'Replace sensor battery.'
      - service: notify.nexus5x
        data:
          title: 'Replace sensor battery'
          message: 'Replace sensor battery.'
```
