### ISSUE TITLE
MQTT w/ Owntracks for presence detection

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#15]
- [ ] [Owntracks](https://home-assistant.io/components/device_tracker.owntracks/)
- [ ] [MQTT](https://home-assistant.io/components/mqtt/)
- [ ] [MQTT Device Tracker](https://home-assistant.io/components/device_tracker.mqtt/)
- [ ] [MQTT Room Presence Detection](https://home-assistant.io/components/sensor.mqtt_room/)

**Comment by brianjking** [comment]
Old TP-Link Device Tracker YAML configuration

````yaml
device_tracker:
  - platform: tplink
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password 
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no
````
