### ISSUE TITLE
Tile Trackers on Raspberry Pi -- Investigating

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#163]
https://community.home-assistant.io/t/bluetooth-presence-detection-without-raspberry-pi-3/35558/4?u=brianjking

**Comment by brianjking** [comment]
```
sudo apt-get install python3-pip libglib2.0-dev python-flask

sudo pip3 install bluepy
```

```python
from flask import Flask
from bluepy.btle import Scanner, DefaultDelegate

class ScanDelegate(DefaultDelegate):
    def __init__(self):
        DefaultDelegate.__init__(self)

    def handleDiscovery(self, dev, isNewDev, isNewData):
        return()

scanner = Scanner().withDelegate(ScanDelegate())

app = Flask(__name__)

@app.route('/api/search/<string:mac_addr>', methods=['GET'])
def device_scan(mac_addr):
    scanner = Scanner().withDelegate(ScanDelegate())
    devices = scanner.scan(3.0)
    for dev in devices:
        if dev.addr == mac_addr:
            return("true")
    return("false")

@app.errorhandler(404)
def not_found(error):
    return("Not Found ", error)

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=False)
```

```yaml
## Presense / Tiles Sensor via Pi Zero Hassbian

  - platform: rest
    name: Car Keys
    resource: http://192.168.18.143:5000/api/search/a4:e8:27:f4:3e:2a
```

```
sudo hcitool lescan
```

* NOTE: `MAC address` must be in lowercase
* NOTE 2: When Tiles are paired with the Tile Android app they do not broadcast a `MAC address`.
