### ISSUE TITLE
Rainy Day Automation

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#61]

**Comment by brianjking** [comment]
```yaml
- alias: Rainy Day
  trigger:
    platform: state
    entity_id: sensor.precip_intensity
    state: 'rain'
    condition:
      - platform: state
        entity_id: group.all_devices
        state: 'home'
      - platform: time
        after: '14:00'
        before: '23:00'
    action:
      service: homeassistant.turn_on
      entity_id: group.livingroom_lights

- alias: Rain is over
  trigger:
    - platform: state
      entity_id: sensor.precip_intensity
      state: 'None'
  condition:
    - condition: sun
      after: 'sunset'
  action:
    service: homeassistant.turn_off
    entity_id: group.livingroom_lights 
```
