### ISSUE TITLE
Crime Reports Sensors

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#67]
https://github.com/happyleavesaoc/my-home-automation/blob/master/homeassistant/sensors/crimereports.yaml

```yaml
- platform: crimereports
  zone: 'neighborhood'
  exclude: ['Community Policing']
```
