### ISSUE TITLE
Notify if door left open

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#68]
```yaml
alias: Alert if the front door was left open
trigger:
  platform: state
  entity_id: sensor.door_two
  state: 'off'
  for:
    seconds: 120
action:
  - service: notify.all
    data_template:
      message: 'Front door is open! Please close it.'
```

**Comment by brianjking** [comment]
binary_sensor.ecolink_doorwindow_sensor_sensor_4_0

**Comment by brianjking** [comment]
https://github.com/brianjking/homeassistant-config/blob/master/automation/front-door-open-alert.yaml

```yaml
- alias: Front Door Open Notification
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_doorwindow_sensor_sensor_4_0
    state: 'on'
    for:
      seconds: 15
  action:
  - service: notify.simplepush
    data_template:
      message: 'Front door is open!'
```
