### ISSUE TITLE
Enhance Lyft Sensor with Templates to display Time & Price together

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#72]
https://github.com/brianjking/homeassistant-config/blob/master/sensor/lyft.yaml

![image](https://cloud.githubusercontent.com/assets/6786817/24876541/b55a341e-1df1-11e7-8db8-15bd88c2f1ae.png)

```yaml
- platform: lyft
  client_id: !secret lyftclientid
  client_secret: !secret lyftclientsecret
  start_latitude: !secret lyftstartlatitude
  start_longitude: !secret lyftstartlongitude
  end_latitude: !secret endlatitudelyft
  end_longitude: !secret endlongitudelyft
  product_ids:
    - 'lyft'
    - 'lyft_plus'
    - 'lyft_line'
```
