### ISSUE TITLE
Announce Package Config -- For Later

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#81]
```yaml
- alias: Announce package delivery
  trigger:
      platform: state
      entity_id: sensor.deliveries_today
  condition:
      - condition: template
        value_template: '{{trigger.to_state.state|int > trigger.from_state.state|int}}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
  action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.google_play__blackbox
          message: "A package was just delivered."
```
