### ISSUE TITLE
Move new commits sensor from configuration.yaml to standalone file

### ISSUE THREAD

**Issue by brianjking** [brianjking/homeassistant-config#90]
```yaml
sensor 6:
  - platform: template
    sensors: 
      new_commits:
        value_template: >
          {{ states("sensor.new_commits") }}
```
